

using System;
using System.Collections.Generic;
using System.Linq;

namespace GidIndustrial.Gideon.WebApi.Libraries {
    class MimeTypesConverter {
        public static string AddExtensionIfNotPresentBasedOnMimeType(string fileName, string mimeType) {
            if(mimeType == null)
                return fileName;
            var parts = fileName.Split('.');
            var correctExtensionsList = MimeTypesConverter.GetExtensionsByMimeType(mimeType);
            if (correctExtensionsList == null)
                return fileName;

            if (parts.Length > 1) {
                var extension = parts[parts.Length - 1].ToLower();
                if (correctExtensionsList.Contains(extension)) {
                    return fileName;
                }
            }
            return fileName + "." + correctExtensionsList[0];
        }
        public static string[] GetExtensionsByMimeType(string mimeType) {
            return MimeTypesConverter.ExtensionsByMimeType.GetValueOrDefault(mimeType.ToLower());
        }
        private static readonly Dictionary<string, string[]> ExtensionsByMimeType = new Dictionary<string, string[]>{
            {"application/vnd.lotus-1-2-3", new string[]{"123"}},
            {"text/vnd.in3d.3dml", new string[]{"3dml"}},
            {"image/x-3ds", new string[]{"3ds"}},
            {"video/3gpp2", new string[]{"3g2"}},
            {"video/3gpp", new string[]{"3gp"}},
            {"application/x-7z-compressed", new string[]{"7z"}},
            {"application/x-authorware-bin", new string[]{"aab", "u32", "vox", "x32"}},
            {"audio/x-aac", new string[]{"aac"}},
            {"application/x-authorware-map", new string[]{"aam"}},
            {"application/x-authorware-seg", new string[]{"aas"}},
            {"application/x-abiword", new string[]{"abw"}},
            {"application/pkix-attr-cert", new string[]{"ac"}},
            {"application/vnd.americandynamics.acc", new string[]{"acc"}},
            {"application/x-ace-compressed", new string[]{"ace"}},
            {"application/vnd.acucobol", new string[]{"acu"}},
            {"application/vnd.acucorp", new string[]{"acutc", "atc"}},
            {"audio/adpcm", new string[]{"adp"}},
            {"application/vnd.audiograph", new string[]{"aep"}},
            {"application/x-font-type1", new string[]{"afm", "pfa", "pfb", "pfm"}},
            {"application/vnd.ibm.modcap", new string[]{"afp", "list3820", "listafp"}},
            {"application/vnd.ahead.space", new string[]{"ahead"}},
            {"application/postscript", new string[]{"ai", "eps", "ps"}},
            {"audio/x-aiff", new string[]{"aif", "aifc", "aiff"}},
            {"application/vnd.adobe.air-application-installer-package+zip", new string[]{"air"}},
            {"application/vnd.dvb.ait", new string[]{"ait"}},
            {"application/vnd.amiga.ami", new string[]{"ami"}},
            {"application/vnd.android.package-archive", new string[]{"apk"}},
            {"text/cache-manifest", new string[]{"appcache"}},
            {"application/x-ms-application", new string[]{"application"}},
            {"application/vnd.lotus-approach", new string[]{"apr"}},
            {"application/x-freearc", new string[]{"arc"}},
            {"application/pgp-signature", new string[]{"asc", "sig"}},
            {"video/x-ms-asf", new string[]{"asf", "asx"}},
            {"text/x-asm", new string[]{"asm", "s"}},
            {"application/vnd.accpac.simply.aso", new string[]{"aso"}},
            {"application/atom+xml", new string[]{"atom"}},
            {"application/atomcat+xml", new string[]{"atomcat"}},
            {"application/atomsvc+xml", new string[]{"atomsvc"}},
            {"application/vnd.antix.game-component", new string[]{"atx"}},
            {"audio/basic", new string[]{"au", "snd"}},
            {"video/x-msvideo", new string[]{"avi"}},
            {"application/applixware", new string[]{"aw"}},
            {"application/vnd.airzip.filesecure.azf", new string[]{"azf"}},
            {"application/vnd.airzip.filesecure.azs", new string[]{"azs"}},
            {"application/vnd.amazon.ebook", new string[]{"azw"}},
            {"application/x-msdownload", new string[]{"bat", "com", "dll", "exe", "msi"}},
            {"application/x-bcpio", new string[]{"bcpio"}},
            {"application/x-font-bdf", new string[]{"bdf"}},
            {"application/vnd.syncml.dm+wbxml", new string[]{"bdm"}},
            {"application/vnd.realvnc.bed", new string[]{"bed"}},
            {"application/vnd.fujitsu.oasysprs", new string[]{"bh2"}},
            {"application/octet-stream", new string[]{"bin", "bpk", "deploy", "dist", "distz", "dms", "dump", "elc", "lrf", "mar", "pkg", "so"}},
            {"application/x-blorb", new string[]{"blb", "blorb"}},
            {"application/vnd.bmi", new string[]{"bmi"}},
            {"image/bmp", new string[]{"bmp"}},
            {"application/vnd.framemaker", new string[]{"book", "fm", "frame", "maker"}},
            {"application/vnd.previewsystems.box", new string[]{"box"}},
            {"application/x-bzip2", new string[]{"boz", "bz2"}},
            {"image/prs.btif", new string[]{"btif"}},
            {"application/x-bzip", new string[]{"bz"}},
            {"text/x-c", new string[]{"c", "cc", "cpp", "cxx", "dic", "h", "hh"}},
            {"application/vnd.cluetrust.cartomobile-config", new string[]{"c11amc"}},
            {"application/vnd.cluetrust.cartomobile-config-pkg", new string[]{"c11amz"}},
            {"application/vnd.clonk.c4group", new string[]{"c4d", "c4f", "c4g", "c4p", "c4u"}},
            {"application/vnd.ms-cab-compressed", new string[]{"cab"}},
            {"audio/x-caf", new string[]{"caf"}},
            {"application/vnd.tcpdump.pcap", new string[]{"cap", "dmp", "pcap"}},
            {"application/vnd.curl.car", new string[]{"car"}},
            {"application/vnd.ms-pki.seccat", new string[]{"cat"}},
            {"application/x-cbr", new string[]{"cb7", "cba", "cbr", "cbt", "cbz"}},
            {"application/x-director", new string[]{"cct", "cst", "cxt", "dcr", "dir", "dxr", "fgd", "swa", "w3d"}},
            {"application/ccxml+xml", new string[]{"ccxml"}},
            {"application/vnd.contact.cmsg", new string[]{"cdbcmsg"}},
            {"application/x-netcdf", new string[]{"cdf", "nc"}},
            {"application/vnd.mediastation.cdkey", new string[]{"cdkey"}},
            {"application/cdmi-capability", new string[]{"cdmia"}},
            {"application/cdmi-container", new string[]{"cdmic"}},
            {"application/cdmi-domain", new string[]{"cdmid"}},
            {"application/cdmi-object", new string[]{"cdmio"}},
            {"application/cdmi-queue", new string[]{"cdmiq"}},
            {"chemical/x-cdx", new string[]{"cdx"}},
            {"application/vnd.chemdraw+xml", new string[]{"cdxml"}},
            {"application/vnd.cinderella", new string[]{"cdy"}},
            {"application/pkix-cert", new string[]{"cer"}},
            {"application/x-cfs-compressed", new string[]{"cfs"}},
            {"image/cgm", new string[]{"cgm"}},
            {"application/x-chat", new string[]{"chat"}},
            {"application/vnd.ms-htmlhelp", new string[]{"chm"}},
            {"application/vnd.kde.kchart", new string[]{"chrt"}},
            {"chemical/x-cif", new string[]{"cif"}},
            {"application/vnd.anser-web-certificate-issue-initiation", new string[]{"cii"}},
            {"application/vnd.ms-artgalry", new string[]{"cil"}},
            {"application/vnd.claymore", new string[]{"cla"}},
            {"application/java-vm", new string[]{"class"}},
            {"application/vnd.crick.clicker.keyboard", new string[]{"clkk"}},
            {"application/vnd.crick.clicker.palette", new string[]{"clkp"}},
            {"application/vnd.crick.clicker.template", new string[]{"clkt"}},
            {"application/vnd.crick.clicker.wordbank", new string[]{"clkw"}},
            {"application/vnd.crick.clicker", new string[]{"clkx"}},
            {"application/x-msclip", new string[]{"clp"}},
            {"application/vnd.cosmocaller", new string[]{"cmc"}},
            {"chemical/x-cmdf", new string[]{"cmdf"}},
            {"chemical/x-cml", new string[]{"cml"}},
            {"application/vnd.yellowriver-custom-menu", new string[]{"cmp"}},
            {"image/x-cmx", new string[]{"cmx"}},
            {"application/vnd.rim.cod", new string[]{"cod"}},
            {"text/plain", new string[]{"conf", "def", "in", "list", "log", "text", "txt"}},
            {"application/x-cpio", new string[]{"cpio"}},
            {"application/mac-compactpro", new string[]{"cpt"}},
            {"application/x-mscardfile", new string[]{"crd"}},
            {"application/pkix-crl", new string[]{"crl"}},
            {"application/x-x509-ca-cert", new string[]{"crt", "der"}},
            {"application/vnd.rig.cryptonote", new string[]{"cryptonote"}},
            {"application/x-csh", new string[]{"csh"}},
            {"chemical/x-csml", new string[]{"csml"}},
            {"application/vnd.commonspace", new string[]{"csp"}},
            {"text/css", new string[]{"css"}},
            {"text/csv", new string[]{"csv"}},
            {"application/cu-seeme", new string[]{"cu"}},
            {"text/vnd.curl", new string[]{"curl"}},
            {"application/prs.cww", new string[]{"cww"}},
            {"model/vnd.collada+xml", new string[]{"dae"}},
            {"application/vnd.mobius.daf", new string[]{"daf"}},
            {"application/vnd.dart", new string[]{"dart"}},
            {"application/vnd.fdsn.seed", new string[]{"dataless", "seed"}},
            {"application/davmount+xml", new string[]{"davmount"}},
            {"application/docbook+xml", new string[]{"dbk"}},
            {"text/vnd.curl.dcurl", new string[]{"dcurl"}},
            {"application/vnd.oma.dd2+xml", new string[]{"dd2"}},
            {"application/vnd.fujixerox.ddd", new string[]{"ddd"}},
            {"application/x-debian-package", new string[]{"deb", "udeb"}},
            {"application/vnd.dreamfactory", new string[]{"dfac"}},
            {"application/x-dgc-compressed", new string[]{"dgc"}},
            {"application/vnd.mobius.dis", new string[]{"dis"}},
            {"image/vnd.djvu", new string[]{"djv", "djvu"}},
            {"application/x-apple-diskimage", new string[]{"dmg"}},
            {"application/vnd.dna", new string[]{"dna"}},
            {"application/msword", new string[]{"doc", "dot"}},
            {"application/vnd.ms-word.document.macroenabled.12", new string[]{"docm"}},
            {"application/vnd.openxmlformats-officedocument.wordprocessingml.document", new string[]{"docx"}},
            {"application/vnd.ms-word.template.macroenabled.12", new string[]{"dotm"}},
            {"application/vnd.openxmlformats-officedocument.wordprocessingml.template", new string[]{"dotx"}},
            {"application/vnd.osgi.dp", new string[]{"dp"}},
            {"application/vnd.dpgraph", new string[]{"dpg"}},
            {"audio/vnd.dra", new string[]{"dra"}},
            {"text/prs.lines.tag", new string[]{"dsc"}},
            {"application/dssc+der", new string[]{"dssc"}},
            {"application/x-dtbook+xml", new string[]{"dtb"}},
            {"application/xml-dtd", new string[]{"dtd"}},
            {"audio/vnd.dts", new string[]{"dts"}},
            {"audio/vnd.dts.hd", new string[]{"dtshd"}},
            {"video/vnd.dvb.file", new string[]{"dvb"}},
            {"application/x-dvi", new string[]{"dvi"}},
            {"model/vnd.dwf", new string[]{"dwf"}},
            {"image/vnd.dwg", new string[]{"dwg"}},
            {"image/vnd.dxf", new string[]{"dxf"}},
            {"application/vnd.spotfire.dxp", new string[]{"dxp"}},
            {"audio/vnd.nuera.ecelp4800", new string[]{"ecelp4800"}},
            {"audio/vnd.nuera.ecelp7470", new string[]{"ecelp7470"}},
            {"audio/vnd.nuera.ecelp9600", new string[]{"ecelp9600"}},
            {"application/ecmascript", new string[]{"ecma"}},
            {"application/vnd.novadigm.edm", new string[]{"edm"}},
            {"application/vnd.novadigm.edx", new string[]{"edx"}},
            {"application/vnd.picsel", new string[]{"efif"}},
            {"application/vnd.pg.osasli", new string[]{"ei6"}},
            {"application/x-msmetafile", new string[]{"emf", "emz", "wmf"}},
            {"message/rfc822", new string[]{"eml", "mime"}},
            {"application/emma+xml", new string[]{"emma"}},
            {"audio/vnd.digital-winds", new string[]{"eol"}},
            {"application/vnd.ms-fontobject", new string[]{"eot"}},
            {"application/epub+zip", new string[]{"epub"}},
            {"application/vnd.eszigno3+xml", new string[]{"es3", "et3"}},
            {"application/vnd.osgi.subsystem", new string[]{"esa"}},
            {"application/vnd.epson.esf", new string[]{"esf"}},
            {"text/x-setext", new string[]{"etx"}},
            {"application/x-eva", new string[]{"eva"}},
            {"application/x-envoy", new string[]{"evy"}},
            {"application/exi", new string[]{"exi"}},
            {"application/vnd.novadigm.ext", new string[]{"ext"}},
            {"application/andrew-inset", new string[]{"ez"}},
            {"application/vnd.ezpix-album", new string[]{"ez2"}},
            {"application/vnd.ezpix-package", new string[]{"ez3"}},
            {"text/x-fortran", new string[]{"f", "f77", "f90", "for"}},
            {"video/x-f4v", new string[]{"f4v"}},
            {"image/vnd.fastbidsheet", new string[]{"fbs"}},
            {"application/vnd.adobe.formscentral.fcdt", new string[]{"fcdt"}},
            {"application/vnd.isac.fcs", new string[]{"fcs"}},
            {"application/vnd.fdf", new string[]{"fdf"}},
            {"application/vnd.denovo.fcselayout-link", new string[]{"fe_launch"}},
            {"application/vnd.fujitsu.oasysgp", new string[]{"fg5"}},
            {"image/x-freehand", new string[]{"fh", "fh4", "fh5", "fh7", "fhc"}},
            {"application/x-xfig", new string[]{"fig"}},
            {"audio/x-flac", new string[]{"flac"}},
            {"video/x-fli", new string[]{"fli"}},
            {"application/vnd.micrografx.flo", new string[]{"flo"}},
            {"video/x-flv", new string[]{"flv"}},
            {"application/vnd.kde.kivio", new string[]{"flw"}},
            {"text/vnd.fmi.flexstor", new string[]{"flx"}},
            {"text/vnd.fly", new string[]{"fly"}},
            {"application/vnd.frogans.fnc", new string[]{"fnc"}},
            {"image/vnd.fpx", new string[]{"fpx"}},
            {"application/vnd.fsc.weblaunch", new string[]{"fsc"}},
            {"image/vnd.fst", new string[]{"fst"}},
            {"application/vnd.fluxtime.clip", new string[]{"ftc"}},
            {"application/vnd.anser-web-funds-transfer-initiation", new string[]{"fti"}},
            {"video/vnd.fvt", new string[]{"fvt"}},
            {"application/vnd.adobe.fxp", new string[]{"fxp", "fxpl"}},
            {"application/vnd.fuzzysheet", new string[]{"fzs"}},
            {"application/vnd.geoplan", new string[]{"g2w"}},
            {"image/g3fax", new string[]{"g3"}},
            {"application/vnd.geospace", new string[]{"g3w"}},
            {"application/vnd.groove-account", new string[]{"gac"}},
            {"application/x-tads", new string[]{"gam"}},
            {"application/rpki-ghostbusters", new string[]{"gbr"}},
            {"application/x-gca-compressed", new string[]{"gca"}},
            {"model/vnd.gdl", new string[]{"gdl"}},
            {"application/vnd.dynageo", new string[]{"geo"}},
            {"application/vnd.geometry-explorer", new string[]{"gex", "gre"}},
            {"application/vnd.geogebra.file", new string[]{"ggb"}},
            {"application/vnd.geogebra.tool", new string[]{"ggt"}},
            {"application/vnd.groove-help", new string[]{"ghf"}},
            {"image/gif", new string[]{"gif"}},
            {"application/vnd.groove-identity-message", new string[]{"gim"}},
            {"application/gml+xml", new string[]{"gml"}},
            {"application/vnd.gmx", new string[]{"gmx"}},
            {"application/x-gnumeric", new string[]{"gnumeric"}},
            {"application/vnd.flographit", new string[]{"gph"}},
            {"application/gpx+xml", new string[]{"gpx"}},
            {"application/vnd.grafeq", new string[]{"gqf", "gqs"}},
            {"application/srgs", new string[]{"gram"}},
            {"application/x-gramps-xml", new string[]{"gramps"}},
            {"application/vnd.groove-injector", new string[]{"grv"}},
            {"application/srgs+xml", new string[]{"grxml"}},
            {"application/x-font-ghostscript", new string[]{"gsf"}},
            {"application/x-gtar", new string[]{"gtar"}},
            {"application/vnd.groove-tool-message", new string[]{"gtm"}},
            {"model/vnd.gtw", new string[]{"gtw"}},
            {"text/vnd.graphviz", new string[]{"gv"}},
            {"application/gxf", new string[]{"gxf"}},
            {"application/vnd.geonext", new string[]{"gxt"}},
            {"video/h261", new string[]{"h261"}},
            {"video/h263", new string[]{"h263"}},
            {"video/h264", new string[]{"h264"}},
            {"application/vnd.hal+xml", new string[]{"hal"}},
            {"application/vnd.hbci", new string[]{"hbci"}},
            {"application/x-hdf", new string[]{"hdf"}},
            {"application/winhlp", new string[]{"hlp"}},
            {"application/vnd.hp-hpgl", new string[]{"hpgl"}},
            {"application/vnd.hp-hpid", new string[]{"hpid"}},
            {"application/vnd.hp-hps", new string[]{"hps"}},
            {"application/mac-binhex40", new string[]{"hqx"}},
            {"application/vnd.kenameaapp", new string[]{"htke"}},
            {"text/html", new string[]{"html", "htm"}},
            {"application/vnd.yamaha.hv-dic", new string[]{"hvd"}},
            {"application/vnd.yamaha.hv-voice", new string[]{"hvp"}},
            {"application/vnd.yamaha.hv-script", new string[]{"hvs"}},
            {"application/vnd.intergeo", new string[]{"i2g"}},
            {"application/vnd.iccprofile", new string[]{"icc", "icm"}},
            {"x-conference/x-cooltalk", new string[]{"ice"}},
            {"image/x-icon", new string[]{"ico"}},
            {"text/calendar", new string[]{"ics", "ifb"}},
            {"image/ief", new string[]{"ief"}},
            {"application/vnd.shana.informed.formdata", new string[]{"ifm"}},
            {"model/iges", new string[]{"iges", "igs"}},
            {"application/vnd.igloader", new string[]{"igl"}},
            {"application/vnd.insors.igm", new string[]{"igm"}},
            {"application/vnd.micrografx.igx", new string[]{"igx"}},
            {"application/vnd.shana.informed.interchange", new string[]{"iif"}},
            {"application/vnd.accpac.simply.imp", new string[]{"imp"}},
            {"application/vnd.ms-ims", new string[]{"ims"}},
            {"application/inkml+xml", new string[]{"ink", "inkml"}},
            {"application/x-install-instructions", new string[]{"install"}},
            {"application/vnd.astraea-software.iota", new string[]{"iota"}},
            {"application/ipfix", new string[]{"ipfix"}},
            {"application/vnd.shana.informed.package", new string[]{"ipk"}},
            {"application/vnd.ibm.rights-management", new string[]{"irm"}},
            {"application/vnd.irepository.package+xml", new string[]{"irp"}},
            {"application/x-iso9660-image", new string[]{"iso"}},
            {"application/vnd.shana.informed.formtemplate", new string[]{"itp"}},
            {"application/vnd.immervision-ivp", new string[]{"ivp"}},
            {"application/vnd.immervision-ivu", new string[]{"ivu"}},
            {"text/vnd.sun.j2me.app-descriptor", new string[]{"jad"}},
            {"application/vnd.jam", new string[]{"jam"}},
            {"application/java-archive", new string[]{"jar"}},
            {"text/x-java-source", new string[]{"java"}},
            {"application/vnd.jisp", new string[]{"jisp"}},
            {"application/vnd.hp-jlyt", new string[]{"jlt"}},
            {"application/x-java-jnlp-file", new string[]{"jnlp"}},
            {"application/vnd.joost.joda-archive", new string[]{"joda"}},
            {"image/jpeg", new string[]{"jpg", "jpe", "jpeg"}},
            {"video/jpm", new string[]{"jpgm", "jpm"}},
            {"video/jpeg", new string[]{"jpgv"}},
            {"application/javascript", new string[]{"js"}},
            {"application/json", new string[]{"json"}},
            {"application/jsonml+json", new string[]{"jsonml"}},
            {"audio/midi", new string[]{"kar", "mid", "midi", "rmi"}},
            {"application/vnd.kde.karbon", new string[]{"karbon"}},
            {"application/vnd.kde.kformula", new string[]{"kfo"}},
            {"application/vnd.kidspiration", new string[]{"kia"}},
            {"application/vnd.google-earth.kml+xml", new string[]{"kml"}},
            {"application/vnd.google-earth.kmz", new string[]{"kmz"}},
            {"application/vnd.kinar", new string[]{"kne", "knp"}},
            {"application/vnd.kde.kontour", new string[]{"kon"}},
            {"application/vnd.kde.kpresenter", new string[]{"kpr", "kpt"}},
            {"application/vnd.ds-keypoint", new string[]{"kpxx"}},
            {"application/vnd.kde.kspread", new string[]{"ksp"}},
            {"application/vnd.kahootz", new string[]{"ktr", "ktz"}},
            {"image/ktx", new string[]{"ktx"}},
            {"application/vnd.kde.kword", new string[]{"kwd", "kwt"}},
            {"application/vnd.las.las+xml", new string[]{"lasxml"}},
            {"application/x-latex", new string[]{"latex"}},
            {"application/vnd.llamagraphics.life-balance.desktop", new string[]{"lbd"}},
            {"application/vnd.llamagraphics.life-balance.exchange+xml", new string[]{"lbe"}},
            {"application/vnd.hhe.lesson-player", new string[]{"les"}},
            {"application/x-lzh-compressed", new string[]{"lha", "lzh"}},
            {"application/vnd.route66.link66+xml", new string[]{"link66"}},
            {"application/x-ms-shortcut", new string[]{"lnk"}},
            {"application/lost+xml", new string[]{"lostxml"}},
            {"application/vnd.ms-lrm", new string[]{"lrm"}},
            {"application/vnd.frogans.ltf", new string[]{"ltf"}},
            {"audio/vnd.lucent.voice", new string[]{"lvp"}},
            {"application/vnd.lotus-wordpro", new string[]{"lwp"}},
            {"application/x-msmediaview", new string[]{"m13", "m14", "mvb"}},
            {"video/mpeg", new string[]{"m1v", "m2v", "mpe", "mpeg", "mpg"}},
            {"application/mp21", new string[]{"m21", "mp21"}},
            {"audio/mpeg", new string[]{"m2a", "m3a", "mp2", "mp2a", "mp3", "mpga"}},
            {"audio/x-mpegurl", new string[]{"m3u"}},
            {"application/vnd.apple.mpegurl", new string[]{"m3u8"}},
            {"audio/mp4", new string[]{"m4a", "mp4a"}},
            {"video/vnd.mpegurl", new string[]{"m4u", "mxu"}},
            {"video/x-m4v", new string[]{"m4v"}},
            {"application/mathematica", new string[]{"ma", "mb", "nb"}},
            {"application/mads+xml", new string[]{"mads"}},
            {"application/vnd.ecowin.chart", new string[]{"mag"}},
            {"text/troff", new string[]{"man", "me", "ms", "roff", "t", "tr"}},
            {"application/mathml+xml", new string[]{"mathml"}},
            {"application/vnd.mobius.mbk", new string[]{"mbk"}},
            {"application/mbox", new string[]{"mbox"}},
            {"application/vnd.medcalcdata", new string[]{"mc1"}},
            {"application/vnd.mcd", new string[]{"mcd"}},
            {"text/vnd.curl.mcurl", new string[]{"mcurl"}},
            {"application/x-msaccess", new string[]{"mdb"}},
            {"image/vnd.ms-modi", new string[]{"mdi"}},
            {"model/mesh", new string[]{"mesh", "msh", "silo"}},
            {"application/metalink4+xml", new string[]{"meta4"}},
            {"application/metalink+xml", new string[]{"metalink"}},
            {"application/mets+xml", new string[]{"mets"}},
            {"application/vnd.mfmp", new string[]{"mfm"}},
            {"application/rpki-manifest", new string[]{"mft"}},
            {"application/vnd.osgeo.mapguide.package", new string[]{"mgp"}},
            {"application/vnd.proteus.magazine", new string[]{"mgz"}},
            {"application/x-mie", new string[]{"mie"}},
            {"application/vnd.mif", new string[]{"mif"}},
            {"video/mj2", new string[]{"mj2", "mjp2"}},
            {"video/x-matroska", new string[]{"mk3d", "mks", "mkv"}},
            {"audio/x-matroska", new string[]{"mka"}},
            {"application/vnd.dolby.mlp", new string[]{"mlp"}},
            {"application/vnd.chipnuts.karaoke-mmd", new string[]{"mmd"}},
            {"application/vnd.smaf", new string[]{"mmf"}},
            {"image/vnd.fujixerox.edmics-mmr", new string[]{"mmr"}},
            {"video/x-mng", new string[]{"mng"}},
            {"application/x-msmoney", new string[]{"mny"}},
            {"application/x-mobipocket-ebook", new string[]{"mobi", "prc"}},
            {"application/mods+xml", new string[]{"mods"}},
            {"video/quicktime", new string[]{"mov", "qt"}},
            {"video/x-sgi-movie", new string[]{"movie"}},
            {"video/mp4", new string[]{"mp4", "mp4v", "mpg4"}},
            {"application/mp4", new string[]{"mp4s"}},
            {"application/vnd.mophun.certificate", new string[]{"mpc"}},
            {"application/vnd.apple.installer+xml", new string[]{"mpkg"}},
            {"application/vnd.blueice.multipass", new string[]{"mpm"}},
            {"application/vnd.mophun.application", new string[]{"mpn"}},
            {"application/vnd.ms-project", new string[]{"mpp", "mpt"}},
            {"application/vnd.ibm.minipay", new string[]{"mpy"}},
            {"application/vnd.mobius.mqy", new string[]{"mqy"}},
            {"application/marc", new string[]{"mrc"}},
            {"application/marcxml+xml", new string[]{"mrcx"}},
            {"application/mediaservercontrol+xml", new string[]{"mscml"}},
            {"application/vnd.fdsn.mseed", new string[]{"mseed"}},
            {"application/vnd.mseq", new string[]{"mseq"}},
            {"application/vnd.epson.msf", new string[]{"msf"}},
            {"application/vnd.mobius.msl", new string[]{"msl"}},
            {"application/vnd.muvee.style", new string[]{"msty"}},
            {"model/vnd.mts", new string[]{"mts"}},
            {"application/vnd.musician", new string[]{"mus"}},
            {"application/vnd.recordare.musicxml+xml", new string[]{"musicxml"}},
            {"application/vnd.mfer", new string[]{"mwf"}},
            {"application/mxf", new string[]{"mxf"}},
            {"application/vnd.recordare.musicxml", new string[]{"mxl"}},
            {"application/xv+xml", new string[]{"mxml", "xhvml", "xvm", "xvml"}},
            {"application/vnd.triscape.mxs", new string[]{"mxs"}},
            {"text/n3", new string[]{"n3"}},
            {"application/vnd.wolfram.player", new string[]{"nbp"}},
            {"application/x-dtbncx+xml", new string[]{"ncx"}},
            {"text/x-nfo", new string[]{"nfo"}},
            {"application/vnd.nokia.n-gage.symbian.install", new string[]{"n-gage"}},
            {"application/vnd.nokia.n-gage.data", new string[]{"ngdat"}},
            {"application/vnd.nitf", new string[]{"nitf", "ntf"}},
            {"application/vnd.neurolanguage.nlu", new string[]{"nlu"}},
            {"application/vnd.enliven", new string[]{"nml"}},
            {"application/vnd.noblenet-directory", new string[]{"nnd"}},
            {"application/vnd.noblenet-sealer", new string[]{"nns"}},
            {"application/vnd.noblenet-web", new string[]{"nnw"}},
            {"image/vnd.net-fpx", new string[]{"npx"}},
            {"application/x-conference", new string[]{"nsc"}},
            {"application/vnd.lotus-notes", new string[]{"nsf"}},
            {"application/x-nzb", new string[]{"nzb"}},
            {"application/vnd.fujitsu.oasys2", new string[]{"oa2"}},
            {"application/vnd.fujitsu.oasys3", new string[]{"oa3"}},
            {"application/vnd.fujitsu.oasys", new string[]{"oas"}},
            {"application/x-msbinder", new string[]{"obd"}},
            {"application/x-tgif", new string[]{"obj"}},
            {"application/oda", new string[]{"oda"}},
            {"application/vnd.oasis.opendocument.database", new string[]{"odb"}},
            {"application/vnd.oasis.opendocument.chart", new string[]{"odc"}},
            {"application/vnd.oasis.opendocument.formula", new string[]{"odf"}},
            {"application/vnd.oasis.opendocument.formula-template", new string[]{"odft"}},
            {"application/vnd.oasis.opendocument.graphics", new string[]{"odg"}},
            {"application/vnd.oasis.opendocument.image", new string[]{"odi"}},
            {"application/vnd.oasis.opendocument.text-master", new string[]{"odm"}},
            {"application/vnd.oasis.opendocument.presentation", new string[]{"odp"}},
            {"application/vnd.oasis.opendocument.spreadsheet", new string[]{"ods"}},
            {"application/vnd.oasis.opendocument.text", new string[]{"odt"}},
            {"audio/ogg", new string[]{"oga", "ogg", "spx"}},
            {"video/ogg", new string[]{"ogv"}},
            {"application/ogg", new string[]{"ogx"}},
            {"application/omdoc+xml", new string[]{"omdoc"}},
            {"application/onenote", new string[]{"onepkg", "onetmp", "onetoc", "onetoc2"}},
            {"application/oebps-package+xml", new string[]{"opf"}},
            {"text/x-opml", new string[]{"opml"}},
            {"application/vnd.palm", new string[]{"oprc", "pdb", "pqa"}},
            {"application/vnd.lotus-organizer", new string[]{"org"}},
            {"application/vnd.yamaha.openscoreformat", new string[]{"osf"}},
            {"application/vnd.yamaha.openscoreformat.osfpvg+xml", new string[]{"osfpvg"}},
            {"application/vnd.oasis.opendocument.chart-template", new string[]{"otc"}},
            {"font/otf", new string[]{"otf"}},
            {"application/vnd.oasis.opendocument.graphics-template", new string[]{"otg"}},
            {"application/vnd.oasis.opendocument.text-web", new string[]{"oth"}},
            {"application/vnd.oasis.opendocument.image-template", new string[]{"oti"}},
            {"application/vnd.oasis.opendocument.presentation-template", new string[]{"otp"}},
            {"application/vnd.oasis.opendocument.spreadsheet-template", new string[]{"ots"}},
            {"application/vnd.oasis.opendocument.text-template", new string[]{"ott"}},
            {"application/oxps", new string[]{"oxps"}},
            {"application/vnd.openofficeorg.extension", new string[]{"oxt"}},
            {"text/x-pascal", new string[]{"p", "pas"}},
            {"application/pkcs10", new string[]{"p10"}},
            {"application/x-pkcs12", new string[]{"p12", "pfx"}},
            {"application/x-pkcs7-certificates", new string[]{"p7b", "spc"}},
            {"application/pkcs7-mime", new string[]{"p7c", "p7m"}},
            {"application/x-pkcs7-certreqresp", new string[]{"p7r"}},
            {"application/pkcs7-signature", new string[]{"p7s"}},
            {"application/pkcs8", new string[]{"p8"}},
            {"application/vnd.pawaafile", new string[]{"paw"}},
            {"application/vnd.powerbuilder6", new string[]{"pbd"}},
            {"image/x-portable-bitmap", new string[]{"pbm"}},
            {"application/x-font-pcf", new string[]{"pcf"}},
            {"application/vnd.hp-pcl", new string[]{"pcl"}},
            {"application/vnd.hp-pclxl", new string[]{"pclxl"}},
            {"image/x-pict", new string[]{"pct", "pic"}},
            {"application/vnd.curl.pcurl", new string[]{"pcurl"}},
            {"image/x-pcx", new string[]{"pcx"}},
            {"application/pdf", new string[]{"pdf"}},
            {"application/font-tdpfr", new string[]{"pfr"}},
            {"image/x-portable-graymap", new string[]{"pgm"}},
            {"application/x-chess-pgn", new string[]{"pgn"}},
            {"application/pgp-encrypted", new string[]{"pgp"}},
            {"application/pkixcmp", new string[]{"pki"}},
            {"application/pkix-pkipath", new string[]{"pkipath"}},
            {"application/vnd.3gpp.pic-bw-large", new string[]{"plb"}},
            {"application/vnd.mobius.plc", new string[]{"plc"}},
            {"application/vnd.pocketlearn", new string[]{"plf"}},
            {"application/pls+xml", new string[]{"pls"}},
            {"application/vnd.ctc-posml", new string[]{"pml"}},
            {"image/png", new string[]{"png"}},
            {"image/x-portable-anymap", new string[]{"pnm"}},
            {"application/vnd.macports.portpkg", new string[]{"portpkg"}},
            {"application/vnd.ms-powerpoint", new string[]{"pot", "pps", "ppt"}},
            {"application/vnd.ms-powerpoint.template.macroenabled.12", new string[]{"potm"}},
            {"application/vnd.openxmlformats-officedocument.presentationml.template", new string[]{"potx"}},
            {"application/vnd.ms-powerpoint.addin.macroenabled.12", new string[]{"ppam"}},
            {"application/vnd.cups-ppd", new string[]{"ppd"}},
            {"image/x-portable-pixmap", new string[]{"ppm"}},
            {"application/vnd.ms-powerpoint.slideshow.macroenabled.12", new string[]{"ppsm"}},
            {"application/vnd.openxmlformats-officedocument.presentationml.slideshow", new string[]{"ppsx"}},
            {"application/vnd.ms-powerpoint.presentation.macroenabled.12", new string[]{"pptm"}},
            {"application/vnd.openxmlformats-officedocument.presentationml.presentation", new string[]{"pptx"}},
            {"application/vnd.lotus-freelance", new string[]{"pre"}},
            {"application/pics-rules", new string[]{"prf"}},
            {"application/vnd.3gpp.pic-bw-small", new string[]{"psb"}},
            {"image/vnd.adobe.photoshop", new string[]{"psd"}},
            {"application/x-font-linux-psf", new string[]{"psf"}},
            {"application/pskc+xml", new string[]{"pskcxml"}},
            {"application/vnd.pvi.ptid1", new string[]{"ptid"}},
            {"application/x-mspublisher", new string[]{"pub"}},
            {"application/vnd.3gpp.pic-bw-var", new string[]{"pvb"}},
            {"application/vnd.3m.post-it-notes", new string[]{"pwn"}},
            {"audio/vnd.ms-playready.media.pya", new string[]{"pya"}},
            {"video/vnd.ms-playready.media.pyv", new string[]{"pyv"}},
            {"application/vnd.epson.quickanime", new string[]{"qam"}},
            {"application/vnd.intu.qbo", new string[]{"qbo"}},
            {"application/vnd.intu.qfx", new string[]{"qfx"}},
            {"application/vnd.publishare-delta-tree", new string[]{"qps"}},
            {"application/vnd.quark.quarkxpress", new string[]{"qwd", "qwt", "qxb", "qxd", "qxl", "qxt"}},
            {"audio/x-pn-realaudio", new string[]{"ra", "ram"}},
            {"application/x-rar-compressed", new string[]{"rar"}},
            {"image/x-cmu-raster", new string[]{"ras"}},
            {"application/vnd.ipunplugged.rcprofile", new string[]{"rcprofile"}},
            {"application/rdf+xml", new string[]{"rdf"}},
            {"application/vnd.data-vision.rdz", new string[]{"rdz"}},
            {"application/vnd.businessobjects", new string[]{"rep"}},
            {"application/x-dtbresource+xml", new string[]{"res"}},
            {"image/x-rgb", new string[]{"rgb"}},
            {"application/reginfo+xml", new string[]{"rif"}},
            {"audio/vnd.rip", new string[]{"rip"}},
            {"application/x-research-info-systems", new string[]{"ris"}},
            {"application/resource-lists+xml", new string[]{"rl"}},
            {"image/vnd.fujixerox.edmics-rlc", new string[]{"rlc"}},
            {"application/resource-lists-diff+xml", new string[]{"rld"}},
            {"application/vnd.rn-realmedia", new string[]{"rm"}},
            {"audio/x-pn-realaudio-plugin", new string[]{"rmp"}},
            {"application/vnd.jcp.javame.midlet-rms", new string[]{"rms"}},
            {"application/vnd.rn-realmedia-vbr", new string[]{"rmvb"}},
            {"application/relax-ng-compact-syntax", new string[]{"rnc"}},
            {"application/rpki-roa", new string[]{"roa"}},
            {"application/vnd.cloanto.rp9", new string[]{"rp9"}},
            {"application/vnd.nokia.radio-presets", new string[]{"rpss"}},
            {"application/vnd.nokia.radio-preset", new string[]{"rpst"}},
            {"application/sparql-query", new string[]{"rq"}},
            {"application/rls-services+xml", new string[]{"rs"}},
            {"application/rsd+xml", new string[]{"rsd"}},
            {"application/rss+xml", new string[]{"rss"}},
            {"application/rtf", new string[]{"rtf"}},
            {"text/richtext", new string[]{"rtx"}},
            {"audio/s3m", new string[]{"s3m"}},
            {"application/vnd.yamaha.smaf-audio", new string[]{"saf"}},
            {"application/sbml+xml", new string[]{"sbml"}},
            {"application/vnd.ibm.secure-container", new string[]{"sc"}},
            {"application/x-msschedule", new string[]{"scd"}},
            {"application/vnd.lotus-screencam", new string[]{"scm"}},
            {"application/scvp-cv-request", new string[]{"scq"}},
            {"application/scvp-cv-response", new string[]{"scs"}},
            {"text/vnd.curl.scurl", new string[]{"scurl"}},
            {"application/vnd.stardivision.draw", new string[]{"sda"}},
            {"application/vnd.stardivision.calc", new string[]{"sdc"}},
            {"application/vnd.stardivision.impress", new string[]{"sdd"}},
            {"application/vnd.solent.sdkm+xml", new string[]{"sdkd", "sdkm"}},
            {"application/sdp", new string[]{"sdp"}},
            {"application/vnd.stardivision.writer", new string[]{"sdw", "vor"}},
            {"application/vnd.seemail", new string[]{"see"}},
            {"application/vnd.sema", new string[]{"sema"}},
            {"application/vnd.semd", new string[]{"semd"}},
            {"application/vnd.semf", new string[]{"semf"}},
            {"application/java-serialized-object", new string[]{"ser"}},
            {"application/set-payment-initiation", new string[]{"setpay"}},
            {"application/set-registration-initiation", new string[]{"setreg"}},
            {"application/vnd.hydrostatix.sof-data", new string[]{"sfd-hdstx"}},
            {"application/vnd.spotfire.sfs", new string[]{"sfs"}},
            {"text/x-sfv", new string[]{"sfv"}},
            {"image/sgi", new string[]{"sgi"}},
            {"application/vnd.stardivision.writer-global", new string[]{"sgl"}},
            {"text/sgml", new string[]{"sgm", "sgml"}},
            {"application/x-sh", new string[]{"sh"}},
            {"application/x-shar", new string[]{"shar"}},
            {"application/shf+xml", new string[]{"shf"}},
            {"image/x-mrsid-image", new string[]{"sid"}},
            {"audio/silk", new string[]{"sil"}},
            {"application/vnd.symbian.install", new string[]{"sis", "sisx"}},
            {"application/x-stuffit", new string[]{"sit"}},
            {"application/x-stuffitx", new string[]{"sitx"}},
            {"application/vnd.koan", new string[]{"skd", "skm", "skp", "skt"}},
            {"application/vnd.ms-powerpoint.slide.macroenabled.12", new string[]{"sldm"}},
            {"application/vnd.openxmlformats-officedocument.presentationml.slide", new string[]{"sldx"}},
            {"application/vnd.epson.salt", new string[]{"slt"}},
            {"application/vnd.stepmania.stepchart", new string[]{"sm"}},
            {"application/vnd.stardivision.math", new string[]{"smf"}},
            {"application/smil+xml", new string[]{"smi", "smil"}},
            {"video/x-smv", new string[]{"smv"}},
            {"application/vnd.stepmania.package", new string[]{"smzip"}},
            {"application/x-font-snf", new string[]{"snf"}},
            {"application/vnd.yamaha.smaf-phrase", new string[]{"spf"}},
            {"application/x-futuresplash", new string[]{"spl"}},
            {"text/vnd.in3d.spot", new string[]{"spot"}},
            {"application/scvp-vp-response", new string[]{"spp"}},
            {"application/scvp-vp-request", new string[]{"spq"}},
            {"application/x-sql", new string[]{"sql"}},
            {"application/x-wais-source", new string[]{"src"}},
            {"application/x-subrip", new string[]{"srt"}},
            {"application/sru+xml", new string[]{"sru"}},
            {"application/sparql-results+xml", new string[]{"srx"}},
            {"application/ssdl+xml", new string[]{"ssdl"}},
            {"application/vnd.kodak-descriptor", new string[]{"sse"}},
            {"application/vnd.epson.ssf", new string[]{"ssf"}},
            {"application/ssml+xml", new string[]{"ssml"}},
            {"application/vnd.sailingtracker.track", new string[]{"st"}},
            {"application/vnd.sun.xml.calc.template", new string[]{"stc"}},
            {"application/vnd.sun.xml.draw.template", new string[]{"std"}},
            {"application/vnd.wt.stf", new string[]{"stf"}},
            {"application/vnd.sun.xml.impress.template", new string[]{"sti"}},
            {"application/hyperstudio", new string[]{"stk"}},
            {"application/vnd.ms-pki.stl", new string[]{"stl"}},
            {"application/vnd.pg.format", new string[]{"str"}},
            {"application/vnd.sun.xml.writer.template", new string[]{"stw"}},
            {"application/vnd.sus-calendar", new string[]{"sus", "susp"}},
            {"application/x-sv4cpio", new string[]{"sv4cpio"}},
            {"application/x-sv4crc", new string[]{"sv4crc"}},
            {"application/vnd.dvb.service", new string[]{"svc"}},
            {"application/vnd.svd", new string[]{"svd"}},
            {"image/svg+xml", new string[]{"svg", "svgz"}},
            {"application/x-shockwave-flash", new string[]{"swf"}},
            {"application/vnd.aristanetworks.swi", new string[]{"swi"}},
            {"application/vnd.sun.xml.calc", new string[]{"sxc"}},
            {"application/vnd.sun.xml.draw", new string[]{"sxd"}},
            {"application/vnd.sun.xml.writer.global", new string[]{"sxg"}},
            {"application/vnd.sun.xml.impress", new string[]{"sxi"}},
            {"application/vnd.sun.xml.math", new string[]{"sxm"}},
            {"application/vnd.sun.xml.writer", new string[]{"sxw"}},
            {"application/x-t3vm-image", new string[]{"t3"}},
            {"application/vnd.mynfc", new string[]{"taglet"}},
            {"application/vnd.tao.intent-module-archive", new string[]{"tao"}},
            {"application/x-tar", new string[]{"tar"}},
            {"application/vnd.3gpp2.tcap", new string[]{"tcap"}},
            {"application/x-tcl", new string[]{"tcl"}},
            {"application/vnd.smart.teacher", new string[]{"teacher"}},
            {"application/tei+xml", new string[]{"tei", "teicorpus"}},
            {"application/x-tex", new string[]{"tex"}},
            {"application/x-texinfo", new string[]{"texi", "texinfo"}},
            {"application/thraud+xml", new string[]{"tfi"}},
            {"application/x-tex-tfm", new string[]{"tfm"}},
            {"image/x-tga", new string[]{"tga"}},
            {"application/vnd.ms-officetheme", new string[]{"thmx"}},
            {"image/tiff", new string[]{"tif", "tiff"}},
            {"application/vnd.tmobile-livetv", new string[]{"tmo"}},
            {"application/x-bittorrent", new string[]{"torrent"}},
            {"application/vnd.groove-tool-template", new string[]{"tpl"}},
            {"application/vnd.trid.tpt", new string[]{"tpt"}},
            {"application/vnd.trueapp", new string[]{"tra"}},
            {"application/x-msterminal", new string[]{"trm"}},
            {"application/timestamped-data", new string[]{"tsd"}},
            {"text/tab-separated-values", new string[]{"tsv"}},
            {"font/collection", new string[]{"ttc"}},
            {"font/ttf", new string[]{"ttf"}},
            {"text/turtle", new string[]{"ttl"}},
            {"application/vnd.simtech-mindmapper", new string[]{"twd", "twds"}},
            {"application/vnd.genomatix.tuxedo", new string[]{"txd"}},
            {"application/vnd.mobius.txf", new string[]{"txf"}},
            {"application/vnd.ufdl", new string[]{"ufd", "ufdl"}},
            {"application/x-glulx", new string[]{"ulx"}},
            {"application/vnd.umajin", new string[]{"umj"}},
            {"application/vnd.unity", new string[]{"unityweb"}},
            {"application/vnd.uoml+xml", new string[]{"uoml"}},
            {"text/uri-list", new string[]{"uri", "uris", "urls"}},
            {"application/x-ustar", new string[]{"ustar"}},
            {"application/vnd.uiq.theme", new string[]{"utz"}},
            {"text/x-uuencode", new string[]{"uu"}},
            {"audio/vnd.dece.audio", new string[]{"uva", "uvva"}},
            {"application/vnd.dece.data", new string[]{"uvd", "uvf", "uvvd", "uvvf"}},
            {"image/vnd.dece.graphic", new string[]{"uvg", "uvi", "uvvg", "uvvi"}},
            {"video/vnd.dece.hd", new string[]{"uvh", "uvvh"}},
            {"video/vnd.dece.mobile", new string[]{"uvm", "uvvm"}},
            {"video/vnd.dece.pd", new string[]{"uvp", "uvvp"}},
            {"video/vnd.dece.sd", new string[]{"uvs", "uvvs"}},
            {"application/vnd.dece.ttml+xml", new string[]{"uvt", "uvvt"}},
            {"video/vnd.uvvu.mp4", new string[]{"uvu", "uvvu"}},
            {"video/vnd.dece.video", new string[]{"uvv", "uvvv"}},
            {"application/vnd.dece.unspecified", new string[]{"uvvx", "uvx"}},
            {"application/vnd.dece.zip", new string[]{"uvvz", "uvz"}},
            {"text/vcard", new string[]{"vcard"}},
            {"application/x-cdlink", new string[]{"vcd"}},
            {"text/x-vcard", new string[]{"vcf"}},
            {"application/vnd.groove-vcard", new string[]{"vcg"}},
            {"text/x-vcalendar", new string[]{"vcs"}},
            {"application/vnd.vcx", new string[]{"vcx"}},
            {"application/vnd.visionary", new string[]{"vis"}},
            {"video/vnd.vivo", new string[]{"viv"}},
            {"video/x-ms-vob", new string[]{"vob"}},
            {"model/vrml", new string[]{"vrml", "wrl"}},
            {"application/vnd.visio", new string[]{"vsd", "vss", "vst", "vsw"}},
            {"application/vnd.vsf", new string[]{"vsf"}},
            {"model/vnd.vtu", new string[]{"vtu"}},
            {"application/voicexml+xml", new string[]{"vxml"}},
            {"application/x-doom", new string[]{"wad"}},
            {"audio/x-wav", new string[]{"wav"}},
            {"audio/x-ms-wax", new string[]{"wax"}},
            {"image/vnd.wap.wbmp", new string[]{"wbmp"}},
            {"application/vnd.criticaltools.wbs+xml", new string[]{"wbs"}},
            {"application/vnd.wap.wbxml", new string[]{"wbxml"}},
            {"application/vnd.ms-works", new string[]{"wcm", "wdb", "wks", "wps"}},
            {"image/vnd.ms-photo", new string[]{"wdp"}},
            {"audio/webm", new string[]{"weba"}},
            {"video/webm", new string[]{"webm"}},
            {"image/webp", new string[]{"webp"}},
            {"application/vnd.pmi.widget", new string[]{"wg"}},
            {"application/widget", new string[]{"wgt"}},
            {"video/x-ms-wm", new string[]{"wm"}},
            {"audio/x-ms-wma", new string[]{"wma"}},
            {"application/x-ms-wmd", new string[]{"wmd"}},
            {"text/vnd.wap.wml", new string[]{"wml"}},
            {"application/vnd.wap.wmlc", new string[]{"wmlc"}},
            {"text/vnd.wap.wmlscript", new string[]{"wmls"}},
            {"application/vnd.wap.wmlscriptc", new string[]{"wmlsc"}},
            {"video/x-ms-wmv", new string[]{"wmv"}},
            {"video/x-ms-wmx", new string[]{"wmx"}},
            {"font/woff", new string[]{"woff"}},
            {"font/woff2", new string[]{"woff2"}},
            {"application/vnd.wordperfect", new string[]{"wpd"}},
            {"application/vnd.ms-wpl", new string[]{"wpl"}},
            {"application/vnd.wqd", new string[]{"wqd"}},
            {"application/x-mswrite", new string[]{"wri"}},
            {"application/wsdl+xml", new string[]{"wsdl"}},
            {"application/wspolicy+xml", new string[]{"wspolicy"}},
            {"application/vnd.webturbo", new string[]{"wtb"}},
            {"video/x-ms-wvx", new string[]{"wvx"}},
            {"model/x3d+xml", new string[]{"x3d", "x3dz"}},
            {"model/x3d+binary", new string[]{"x3db", "x3dbz"}},
            {"model/x3d+vrml", new string[]{"x3dv", "x3dvz"}},
            {"application/xaml+xml", new string[]{"xaml"}},
            {"application/x-silverlight-app", new string[]{"xap"}},
            {"application/vnd.xara", new string[]{"xar"}},
            {"application/x-ms-xbap", new string[]{"xbap"}},
            {"application/vnd.fujixerox.docuworks.binder", new string[]{"xbd"}},
            {"image/x-xbitmap", new string[]{"xbm"}},
            {"application/xcap-diff+xml", new string[]{"xdf"}},
            {"application/vnd.syncml.dm+xml", new string[]{"xdm"}},
            {"application/vnd.adobe.xdp+xml", new string[]{"xdp"}},
            {"application/dssc+xml", new string[]{"xdssc"}},
            {"application/vnd.fujixerox.docuworks", new string[]{"xdw"}},
            {"application/xenc+xml", new string[]{"xenc"}},
            {"application/patch-ops-error+xml", new string[]{"xer"}},
            {"application/vnd.adobe.xfdf", new string[]{"xfdf"}},
            {"application/vnd.xfdl", new string[]{"xfdl"}},
            {"application/xhtml+xml", new string[]{"xht", "xhtml"}},
            {"image/vnd.xiff", new string[]{"xif"}},
            {"application/vnd.ms-excel", new string[]{"xla", "xlc", "xlm", "xls", "xlt", "xlw"}},
            {"application/vnd.ms-excel.addin.macroenabled.12", new string[]{"xlam"}},
            {"application/x-xliff+xml", new string[]{"xlf"}},
            {"application/vnd.ms-excel.sheet.binary.macroenabled.12", new string[]{"xlsb"}},
            {"application/vnd.ms-excel.sheet.macroenabled.12", new string[]{"xlsm"}},
            {"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", new string[]{"xlsx"}},
            {"application/vnd.ms-excel.template.macroenabled.12", new string[]{"xltm"}},
            {"application/vnd.openxmlformats-officedocument.spreadsheetml.template", new string[]{"xltx"}},
            {"audio/xm", new string[]{"xm"}},
            {"application/xml", new string[]{"xml", "xsl"}},
            {"application/vnd.olpc-sugar", new string[]{"xo"}},
            {"application/xop+xml", new string[]{"xop"}},
            {"application/x-xpinstall", new string[]{"xpi"}},
            {"application/xproc+xml", new string[]{"xpl"}},
            {"image/x-xpixmap", new string[]{"xpm"}},
            {"application/vnd.is-xpr", new string[]{"xpr"}},
            {"application/vnd.ms-xpsdocument", new string[]{"xps"}},
            {"application/vnd.intercon.formnet", new string[]{"xpw", "xpx"}},
            {"application/xslt+xml", new string[]{"xslt"}},
            {"application/vnd.syncml+xml", new string[]{"xsm"}},
            {"application/xspf+xml", new string[]{"xspf"}},
            {"application/vnd.mozilla.xul+xml", new string[]{"xul"}},
            {"image/x-xwindowdump", new string[]{"xwd"}},
            {"chemical/x-xyz", new string[]{"xyz"}},
            {"application/x-xz", new string[]{"xz"}},
            {"application/yang", new string[]{"yang"}},
            {"application/yin+xml", new string[]{"yin"}},
            {"application/x-zmachine", new string[]{"z1", "z2", "z3", "z4", "z5", "z6", "z7", "z8"}},
            {"application/vnd.zzazz.deck+xml", new string[]{"zaz"}},
            {"application/zip", new string[]{"zip"}},
            {"application/vnd.zul", new string[]{"zir", "zirz"}},
            {"application/vnd.handheld-entertainment+xml", new string[]{"zmm"}}
        };
    }
}